### ISSUE TITLE
Potential typo?

### ISSUE THREAD

**Issue by thargy** [IntergatedCircuits/hid-usage-tables#4]
https://github.com/IntergatedCircuits/hid-usage-tables/blob/34c63400176fa6d6118897ef4103a14fd3a5f124/pages/000f-physical-input-device.txt#L1

Did you mean to change "Input" to "Interput"?

**Comment by benedekkupper** [comment]
Indeed, that's a typo, thanks for catching it! Fixed on master now.

There is an easter egg in the latest published HID usage tables on the [usb.org/hid](https://usb.org/hid) site, it has a JSON file attachment that can be used for code generation ([Source](https://github.com/microsoft/hidtools/issues/2)). I will most likely keep this repo up to date (as some currently unused information in this format isn't present in the JSON), but for the simple purpose of usage ID name lookup I'd switch over to using the "official" JSON.

**Comment by thargy** [comment]
Thanks for the tip, I'll look into it and let you know if I deprecate the link to you repo (I may not have enough in the spec json to be equivalent) 🤷🏻‍♂️👍🏻

**Comment by thargy** [comment]
Thanks, I have now rewritten my generators to use the PDF file directly and am no longer dependent on this repo. I will leave the acknowledgement in my Readme in recognition of versions 1-2.

**Comment by matwilli** [comment]
@benedekkupper What are the particular fields that are missing from the official HID-WG PDF?  (I looked at a few of your page definitions, and couldn't find anything obvious).  If the fields are generally applicable, I would be open to considering adding them to the HID-WG PDF.

**Comment by benedekkupper** [comment]
@matwilli well there's a lot I can tell about what's missing (or incorrect) from the usage tables document. In no particular order:

### 1. Named Array codomains
The most extended extra effort in my database is that I have tried my best to record the codomain of the Named Array usages, so what the possible expected values a given `NAry` type data field can provide. E.g. on page 0x0B:
```
06 NAry(b0:c2) "Telephony Key Pad"
07 NAry(00090001:0009ffff) "Programmable Button"
```
This information is mostly defined in the document (and put into my database), but it's not transferred into the attached JSON extract.

### 2. Human-readable usage names
There are a few usage pages (e.g. 0x59, or the not yet integrated 0x11 SoC) that are naming their usages in programming language format instead of human readable one. In these cases I have modified the usage names for readability (and also to be able to change from CamelCase to any other programming language format in the code generation). E.g.
> BoundingBoxWidthInMicrometers

becomes *"Bounding Box Width (um)"*

### 3. Sensors page modifiers
The Sensors page (0x20) invents its own version of Usage Switch in the form of "Modifiers" (section 22.2), effectively contradicting the same document, as the Usage Switch is defined in section 3.4.3.5 as a usage type that has a separate usage code, and is applied on the data field's wrapped collection item, instead of OR-ing together two independent fields.

The original Usage Switch definition is a lot clearer and structured, but I believe it's not actually used in any widespread HID application case due to its complexity. The Sensors Usage Switch definition is simpler on the programming side, but creates problems of its own. **At the very least the document should make a clear distinction between the original Usage Switch type, and use another term for the Modifiers used in the Sensors page.**

My real problem with the Sensors Modifiers is that they require a completely separate usage ID handling logic, also for code generation. The document says they apply to all data fields, and this condition must be identified by the name of the usages, meaning that this page needs a unique code generation extension so the data fields are added with all the possible modifiers.

### 4. Sensors page units

The Sensors page also reinvents the units and unit exponents, that are already defined by the HID class specification. It must be made clear, which unit (and exponent) shall be used, the ones taken from the report descriptor's global items, or the sensor usages (also depending on which of these is present for a given data field). I'm seeing contradicting information in different documents.

This is supported by Microsoft's current [HID Sensors Usages document](https://docs.microsoft.com/en-us/windows-hardware/design/whitepapers/hid-sensors-usages):
> As noted in the Specification, Usages have by definition a default Unit of Measure, which will be mentioned in the Usages Table. These default units are noted in sections 1.6 through 1.17.
In no case may the default unit for a sensor supported by the driver be overridden. If units are explicitly specified in the descriptor, note the documented persistence behavior in section 3.9 of the HID usage specification. Units are global items that persist across items until disabling them.

However this is contradicted by the HID Usage Tables v1.3 document, which states:
> Indicates the HID Unit for the Row in the Enumerator’s table. These are used in lieu of explicit Unit() declarations in the HID Report Descriptor for Generic Sensors.

Naturally the sensible solution would be to use the generic HID units, and clarify this in the Usage Tables document (also marking the unit and exponent related usages as deprecated).

### 5. Buffered Bytes
Buffered Bytes usage type is used in 0x14 page, but this usage type is not defined in "3.4.2 Usage Types (Data)" section of the document. It would be well worth to add this, as this usage type has an additional (so far implicit) requirement, that the report descriptor's main item using this usage type should set bit 8 of the item value {Bit Field (0) | Buffered Bytes (1)}.

PS: It's also fun to see that with wide enough adoption usage IDs get added even without HID WG approval (looking at FIDO page).

**Comment by thargy** [comment]
Yup, when I migrated my code base, I had to rip out a lot of cool functionality, particularly around multiple generator support. It would be nice to see the JSON enhanced. If you do please let me know!

**Comment by matwilli** [comment]
*Thanks for all your great feedback; I appreciate the time it took!  Do share if you have any further feedback.*

\# 1 is a good idea.  I thought I had it on my backlog (at some point…) but it's not there now (sigh…).  **I will make this a priority**, integrating into both the JSON definition and Waratah (though it will still likely take till next year to do).  As a point of clarification (for anyone else on this thread), NArys are not limited to only those (typically) beside with the definition; so just as you described, these would only be 'expected' values.

\# 2 I'm not sure about.  PascalCasing was chosen by the author (then approved by the HID-WG), so for all intents/purposes that is its name, no other.  If Usage Names were to be read by non-HID authors, I agree that a space-separated name would be required, as it would need to be more readable (and localizable to other languages).  I do agree that it breaks with the style of (all) the other naming, which isn't good, and it makes it hard to modify to the code-style of other programming-languages.  **I'll think more about this and reach out the HID-WG for their input**.

For \# 3, \# 4, yes I agree the Sensor Page messed up many things, for no good reason, other than (likely) the authors thought it was 'simpler'.  Authoring HID Report Descriptors has been very difficult, and lots of shortcuts have been taken; [Waratah](https://github.com/microsoft/hidtools) is the first step in solving that by making it easier to author descriptors.  Since we're stuck with this approach, **I'll look at adding clarifications to the spec to explain this background**.  (I have the [usageTransform](https://github.com/microsoft/hidtools/wiki/Waratah-Keys#usagetransform) functionality in Waratah to perform this function for Sensors)

#5 Yes, it looks like the term 'Buffered-Bytes' has been mis/used in many places in the document.  **I'll look to scrub the document to make these references clearer.**

Regarding the FIDO page, it was defined/approved via [HUTRR48](https://usb.org/sites/default/files/hutrr48.pdf) by the HID Working Group.  All Usages are reviewed/approved by the HID-WG, by nominated members of the USB-IF.  All other Usages must use Vendor-defined Usages Pages (or ranges), bound to a specific VID+PID.

**Comment by benedekkupper** [comment]
\# 1 I'm glad to hear that this will make it into the official format.

\# 2 The usage names are just that, names that facilitate understanding the meaning of the numeric value of the ID. Surely it would make no difference if only capitalization and whitespaces were changed in these names. (Especially as in this case a human text -> PascalCase conversion function would come to the same result, as what the current name is.)

\# 3-5 I'm happy to hear that the documentation will get some much deserved clarifications.
In my opinion the biggest problem with the HID report descriptor concept is that it's too vague and allows values to be represented in many different ways, without explaining the complexity needed on the host side to interpret all these formats. I still have a copy of HID Usage Tables 1.12, the Appendices contain many very fancy examples, that are however aren't recognized by major OS-es correctly.

My mistake at the FIDO page, it just struck me with its high value page ID and the lack of a referenced HUTRR number in the document.
*Checking this HUTRR it catches my eye that the data usages are marked with DV, where Buffered Bytes would have been more appropriate. Another thing is that now I'm getting confused by the static vs. dynamic qualifier (as in SV - DV). In the Sensors page the measured values are Static, because they are read-only. My previous understanding was that static means constant, and dynamic means variable. After the FIDO page I'm confused again.*

### Let me also broaden the scope of the feedback to the [HID subpage](https://usb.org/hid) in general:
A) It would be great to remove obsolete information and tools from this webpage, and add up-to-date information instead. This should include Waratah and co., and the Usage Tables JSON as a directly accessible download. It would also be nice to see [hid-rdf](https://github.com/IntergatedCircuits/hid-rdf) in there, but that's more wishful thinking on my side.
B) This webpage should also address the fact that HID has greatly outgrown its origins as a USB class, and at least mention that it is also supported over Bluetooth, I2C, SPI and who knows what else other transport protocols. (It might seem counterintuitive to put this information on the USB portal, quasi advertising the alternative transports, in reality these transports aren't interchangeable.)

**Comment by thargy** [comment]
+1 for separate, direct, JSON download. PDF parsing is non-trivial and many tools to extract the attachment are not open source, or not easily usable from every toolchain.

Even the way I do it I'm not super happy with. It seems like a cruel limitation to not have it directly, and formally, accessible.  There should be a latest link, and version specific links. That will make it far more usable in automated toolchains and in more programming environments.

**Comment by matwilli** [comment]
_Apologies for the late reply_

Thanks for the additional feedback; the wheels are in motion.  I'll reply back to this thread once progress is made.

w.r.t bundling the JSON file in the PDF, this was a deliberate decision.  The HID-WG currency is (PDF) documents; these are licensed, copyrighted, versioned, voted-on, published (etc...).  Any separately published files would also need to include these steps.  While do'able, having as an attachment simplifies these processes (as it's still a single document).  It also has the benefit of a single-source-of-truth (i.e. a single 'file'), with 2 formats, PDF and JSON.

I appreciate the limitations with this approach, but since most readers are there for the PDF, publishing additional companion files doesn't yet seem the right thing to do.

**Comment by benedekkupper** [comment]
While I understand the motivation to keep the source materials bundled, I don't see why a ZIP archive containing both the JSON and the PDF (and maybe a third, license file) wouldn't also satisfy all of these requirements.

Also, what exact copyright is applicable to the JSON file, the contents of which are largely equivalent to what is collected in this repository? Is this repository therefore infringing on any copyrights?

**Comment by thargy** [comment]
I'd like to add that JSON is machine-readable format. It's purpose is to be easily parsed by code. Being an attachment in a PDF only emphasises that as the vast majority of users/humans don't realise PDFs can have attachments and wouldn't know it was there unless told (and wouldn't be able to figure out how to access it without calling their friendly support)!

However, placing it as a PDF attachment massively reduces it's accessibility from code as there are almost no OS tools for doing so. In this regard I'm saying so as someone who has 'cracked that egg'; so it makes little difference to my project. However, having it as an easily downloadable JSON would, IMHO, significantly increase its usage and adoption. In its current form I'm pessimistic regarding its real world utility.

I fully understand the bureaucratic reasons for the choice. However, perhaps a solution is to have the JSON extracted from the PDF automatically on the website and published alongside the PDF? Solving the problem once for everyone, rather than forcing everyone to solve the problem themselves? If it were an automated solution it shouldn't get out of sync - mitigating the primary problem of it being a secondary source of truth.

Die hards could still download the PDF and extract the JSON themselves - but I suspect very few will. Meanwhile, the extracted JSON will be readily useable by multiple communities - proving its utility, and make it much more likely to be maintained in future versions.
